version: '3.8'
services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    container_name: advent2020.redis
  frontend:
    build: ./advent2020_frontend
    image: advent2020:frontend
    ports:
      - 3000:3000
    container_name: advent2020.frontend
