version: '3.8'
services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    container_name: advent2020.redis
  api:
    build: 
      context: ./advent2020_api
      dockerfile: Dockerfile.dev
    image: advent2020:api-dev
    environment:
      REDIS_URL: advent2020.redis:6379
    ports:
      - 8000:8000
    volumes:
      - ./advent2020_api/src:/usr/src/advent2020_api/src
    depends_on:
      - redis
    container_name: advent2020.api-dev
  frontend:
    build: ./advent2020_frontend
    image: advent2020:frontend
    ports:
      - 3000:3000
    depends_on:
      - api
    container_name: advent2020.frontend
